export type CalendarEventCategory = "決算" | "経済指標" | "金融政策" | "休場";
export type CalendarEventRegion = "日本" | "米国";
export type CalendarEventImportance = "高" | "中";

export type MarketCalendarForecast = {
  reviewedAt: string;
  values: string[];
  sourceName: string;
  sourceUrl: string;
};

export type MarketCalendarEvent = {
  id: string;
  date: string;
  time: string;
  title: string;
  category: CalendarEventCategory;
  region: CalendarEventRegion;
  importance: CalendarEventImportance;
  summary: string;
  sourceName: string;
  sourceUrl: string;
  sourceTime?: string;
  forecast?: MarketCalendarForecast;
};

export const marketCalendarReviewedAt = "2026-09-06";

export const marketCalendarEvents: MarketCalendarEvent[] = [
  {
    id: "bea-pce-2026-07",
    date: "2026-08-26",
    time: "21:30",
    title: "米個人所得・個人消費支出（2026年7月分）",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "PCE物価と個人消費の確認日。FRBの物価判断と消費関連株の見方に関係しやすい。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule",
    sourceTime: "8月26日 8:30 ET",
    forecast: {
      reviewedAt: "2026-08-23",
      values: [
        "個人所得 前月比 +0.2%",
        "個人消費支出 前月比 +0.1%",
        "PCE価格指数 前月比 +0.1% / 前年比 +3.6%",
        "コアPCE 前月比 +0.2% / 前年比 +3.3%",
      ],
      sourceName: "MarketWatch U.S. Economic Calendar",
      sourceUrl: "https://www.marketwatch.com/economy-politics/calendar",
    },
  },
  {
    id: "bea-gdp-second-2026-q2",
    date: "2026-08-26",
    time: "21:30",
    title: "米GDP 2026年4-6月期・2次推計",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "企業利益とGDP改定の確認日。金利、景気敏感株、ドル円の材料になり得る。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "8月26日 8:30 ET",
    forecast: {
      reviewedAt: "2026-08-23",
      values: ["実質GDP 2次推計 年率 +1.5%"],
      sourceName: "MarketWatch U.S. Economic Calendar",
      sourceUrl: "https://www.marketwatch.com/economy-politics/calendar",
    },
  },
  {
    id: "nvidia-fy27-q2",
    date: "2026-08-27",
    time: "06:00",
    title: "NVIDIA FY2027 Q2 決算説明会",
    category: "決算",
    region: "米国",
    importance: "高",
    summary: "AI半導体、データセンター需要、次世代GPU供給を確認する重要決算。",
    sourceName: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/events-and-presentations/events-and-presentations/event-details/2026/NVIDIA-2nd-Quarter-FY27-Financial-Results/default.aspx",
    sourceTime: "8月26日 14:00 PT",
    forecast: {
      reviewedAt: "2026-08-23",
      values: ["売上高 919億ドル", "調整後EPS 2.08ドル"],
      sourceName: "Investing.com",
      sourceUrl: "https://in.investing.com/news/stock-market-news/nvidia-fiscal-q2-2027-earnings-outlook-what-to-watch-on-august-26-93CH-5567845",
    },
  },
  {
    id: "salesforce-fy27-q2",
    date: "2026-08-27",
    time: "朝",
    title: "Salesforce FY2027 Q2 決算",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "AI機能とソフトウェア需要、サブスクリプション成長の確認材料。",
    sourceName: "Salesforce Investor Relations",
    sourceUrl: "https://investor.salesforce.com/news/news-details/2026/Salesforce-Announces-Date-of-Second-Quarter-Fiscal-2027-Earnings-Release-and-Webcast/default.aspx",
    sourceTime: "8月26日 米国市場引け後",
    forecast: {
      reviewedAt: "2026-08-23",
      values: ["売上高 113.3億ドル", "調整後EPS 3.28ドル"],
      sourceName: "Investopedia / Visible Alpha",
      sourceUrl: "https://www.investopedia.com/here-is-how-much-salesforce-stock-is-expected-to-move-after-earnings-crm-q2-fy2027-12064121",
    },
  },
  {
    id: "tokyo-cpi-2026-08",
    date: "2026-08-28",
    time: "08:30",
    title: "東京都区部CPI 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "全国CPIに先行する物価指標。日銀観測と円金利の確認材料。",
    sourceName: "総務省統計局 消費者物価指数",
    sourceUrl: "https://www.stat.go.jp/data/cpi/sokuhou/tsuki/index-z.html",
    sourceTime: "8月28日 8:30 JST",
    forecast: {
      reviewedAt: "2026-08-23",
      values: ["東京都区部CPI 前年比 +1.9〜2.0%", "コアCPI 前年比 +1.9%"],
      sourceName: "Newsquawk Week in Focus",
      sourceUrl: "https://www.newsquawk.com/content/research_sheets/production/original/000/041/993/Week_in_Focus__24-28th_August_2026__1_.pdf",
    },
  },
  {
    id: "japan-industrial-production-2026-07",
    date: "2026-08-31",
    time: "08:50",
    title: "鉱工業生産・出荷・在庫指数 2026年7月分・速報",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "製造業の生産、出荷、在庫と先行きの生産計画を確認する指標。景気循環や輸出関連企業の動向を見る材料。",
    sourceName: "e-Stat 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar",
    sourceTime: "8月31日 8:50 JST",
  },
  {
    id: "bls-jolts-2026-07",
    date: "2026-09-01",
    time: "23:00",
    title: "米JOLTS求人件数 2026年7月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "求人件数、採用、離職の動きを確認する労働需給指標。雇用統計前の労働市場判断に使われる。",
    sourceName: "BLS September 2026 Release Schedule",
    sourceUrl: "https://www.bls.gov/schedule/2026/09_sched.htm",
    sourceTime: "9月1日 10:00 ET",
  },
  {
    id: "ism-manufacturing-2026-08",
    date: "2026-09-01",
    time: "23:00",
    title: "米ISM製造業景況指数 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "製造業の受注、生産、雇用、価格動向を確認する代表的な景況指数。景気敏感株や金利の材料になりやすい。",
    sourceName: "ISM Report Release Date Calendar",
    sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/rob-report-calendar/",
    sourceTime: "9月1日 10:00 ET",
  },
  {
    id: "dell-fy27-q2",
    date: "2026-09-02",
    time: "05:30",
    title: "Dell Technologies FY2027 Q2 決算説明会",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "AIサーバー需要、インフラ投資、企業IT支出を確認する決算。",
    sourceName: "Dell Technologies Investor Relations",
    sourceUrl: "https://delltechnologies.gcs-web.com/",
    sourceTime: "9月1日 15:30 CDT",
    forecast: {
      reviewedAt: "2026-08-23",
      values: ["EPS 4.89ドル"],
      sourceName: "WSJ / FactSet",
      sourceUrl: "https://www.wsj.com/market-data/quotes/DELL/research-ratings",
    },
  },
  {
    id: "broadcom-fy26-q3",
    date: "2026-09-03",
    time: "06:00",
    title: "Broadcom FY2026 Q3 決算説明会",
    category: "決算",
    region: "米国",
    importance: "高",
    summary: "AI半導体、ネットワーク製品、VMwareを含むインフラソフトウェア事業の成長と次四半期見通しを確認する決算。",
    sourceName: "Broadcom Investor Relations",
    sourceUrl: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announce-third-quarter-fiscal-year-2026-financial",
    sourceTime: "9月2日 14:00 PT",
  },
  {
    id: "ism-services-2026-08",
    date: "2026-09-03",
    time: "23:00",
    title: "米ISM非製造業景況指数 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "米経済の大部分を占めるサービス業の受注、雇用、価格動向を確認する景況指数。",
    sourceName: "ISM Report Release Date Calendar",
    sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/rob-report-calendar/",
    sourceTime: "9月3日 10:00 ET",
  },
  {
    id: "japan-household-spending-2026-07",
    date: "2026-09-04",
    time: "08:30",
    title: "家計調査 2026年7月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "二人以上の世帯の実質消費支出を確認する指標。賃金上昇が個人消費に波及しているかを見る材料。",
    sourceName: "e-Stat 家計調査 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/detail/00200561/202609040830",
    sourceTime: "9月4日 8:30 JST",
  },
  {
    id: "bls-employment-2026-08",
    date: "2026-09-04",
    time: "21:30",
    title: "米雇用統計 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "雇用者数、失業率、賃金の確認日。FRB観測と株式・債券・為替に影響しやすい。",
    sourceName: "BLS Employment Situation Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
    sourceTime: "9月4日 8:30 ET",
  },
  {
    id: "japan-leading-index-2026-07",
    date: "2026-09-07",
    time: "14:00",
    title: "景気動向指数 2026年7月分・速報",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "景気の現状と先行きを示す一致指数・先行指数の速報。国内景気の転換点を機械的に確認する材料。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "9月7日 14:00 JST",
  },
  {
    id: "nyse-labor-day-2026",
    date: "2026-09-07",
    time: "休場",
    title: "NYSE休場（レイバーデー）",
    category: "休場",
    region: "米国",
    importance: "中",
    summary: "米国のレイバーデーに伴うNYSEの休場日。日付は米国市場の取引日基準。",
    sourceName: "NYSE Holidays & Trading Hours",
    sourceUrl: "https://www.nyse.com/trade/hours-calendars",
    sourceTime: "9月7日 米国市場の取引日",
  },
  {
    id: "japan-gdp-second-2026-q2",
    date: "2026-09-08",
    time: "08:50",
    title: "日本GDP 2026年4-6月期・2次速報",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "内需、設備投資、企業収益の改定を確認する日。日本株全体の景気認識に関係する。",
    sourceName: "内閣府 経済社会総合研究所",
    sourceUrl: "https://www.esri.cao.go.jp/jp/sna/kouhyou/kouhyou_top.html",
    sourceTime: "9月8日 8:50 JST",
  },
  {
    id: "japan-monthly-labour-2026-07",
    date: "2026-09-08",
    time: "08:30",
    title: "毎月勤労統計 2026年7月分・速報",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "現金給与総額、実質賃金、労働時間などの動きを確認する統計。",
    sourceName: "e-Stat 毎月勤労統計 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/detail/00450071/202609080830",
    sourceTime: "9月8日 8:30 JST",
  },
  {
    id: "bls-ppi-2026-08",
    date: "2026-09-10",
    time: "21:30",
    title: "米PPI 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "企業の販売価格段階での物価動向を確認する指標。翌日のCPIとあわせてインフレ圧力を見る。",
    sourceName: "BLS PPI Release Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/ppi.htm",
    sourceTime: "9月10日 8:30 ET",
  },
  {
    id: "oracle-fy27-q1",
    date: "2026-09-11",
    time: "06:00",
    title: "Oracle FY2027 Q1 決算説明会",
    category: "決算",
    region: "米国",
    importance: "高",
    summary: "クラウド事業の売上、受注残、設備投資計画を確認する決算説明会。決算資料は米国時間9月10日の市場引け後に公表予定。",
    sourceName: "Oracle Investor Relations",
    sourceUrl: "https://investor.oracle.com/investor-news/news-details/2026/Oracle-Sets-the-Date-for-its-First-Quarter-Fiscal-Year-2027-Earnings-Announcement/default.aspx",
    sourceTime: "9月10日 16:00 CT（夏時間）",
  },
  {
    id: "adobe-fy26-q3",
    date: "2026-09-11",
    time: "06:00",
    title: "Adobe FY2026 Q3 決算説明会",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "クリエイティブ・文書関連サービスの売上、継続課金収入、通期見通しを確認する決算説明会。",
    sourceName: "Adobe Investor Relations",
    sourceUrl: "https://www.adobe.com/investor-relations.html",
    sourceTime: "9月10日 14:00 PT（夏時間）",
  },
  {
    id: "japan-cgpi-2026-08",
    date: "2026-09-11",
    time: "08:50",
    title: "企業物価指数 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "国内企業物価、輸出物価、輸入物価の変化を確認する統計。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "9月11日 8:50 JST",
  },
  {
    id: "japan-business-outlook-2026-q3",
    date: "2026-09-11",
    time: "08:50",
    title: "法人企業景気予測調査 2026年7-9月期",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "企業の景況判断、売上高、利益、設備投資計画を確認する四半期調査。日銀短観前の企業マインド材料。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "9月11日 8:50 JST",
  },
  {
    id: "bls-cpi-2026-08",
    date: "2026-09-11",
    time: "21:30",
    title: "米CPI 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "インフレ再加速の有無を確認する指標。金利、グロース株、ドル円の重要材料。",
    sourceName: "BLS CPI Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
    sourceTime: "9月11日 8:30 ET",
  },
  {
    id: "japan-machinery-orders-2026-07",
    date: "2026-09-16",
    time: "08:50",
    title: "機械受注統計 2026年7月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "設備投資の先行指標。船舶・電力を除く民需の基調から企業の投資姿勢を確認する。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "9月16日 8:50 JST",
  },
  {
    id: "us-retail-sales-2026-08",
    date: "2026-09-16",
    time: "21:30",
    title: "米小売売上高 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "米個人消費の勢いを早期に確認する指標。景気見通しや消費関連企業の判断材料になりやすい。",
    sourceName: "U.S. Census Monthly Retail Trade Schedule",
    sourceUrl: "https://www.census.gov/retail/release_schedule.html",
    sourceTime: "9月16日 8:30 ET",
  },
  {
    id: "fomc-2026-09",
    date: "2026-09-17",
    time: "03:00",
    title: "FOMC声明・政策金利発表",
    category: "金融政策",
    region: "米国",
    importance: "高",
    summary: "SEP付き会合。政策金利、声明文、議長会見、ドットチャートを確認する日。",
    sourceName: "Federal Reserve FOMC Calendars",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceTime: "9月16日 14:00 ET",
  },
  {
    id: "us-housing-starts-2026-08",
    date: "2026-09-17",
    time: "21:30",
    title: "米住宅着工・建設許可件数 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "住宅着工、建設許可、竣工件数から住宅建設の動向を確認する統計。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "9月17日 8:30 ET（夏時間）",
  },
  {
    id: "japan-cpi-2026-08",
    date: "2026-09-18",
    time: "08:30",
    title: "全国CPI 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "日本の物価基調を確認する指標。日銀会合と同日に重なり、円金利の材料になりやすい。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/statistics/00200573",
    sourceTime: "9月18日 8:30 JST",
  },
  {
    id: "boj-mpm-2026-09",
    date: "2026-09-18",
    time: "未定",
    title: "日銀 金融政策決定会合・結果公表",
    category: "金融政策",
    region: "日本",
    importance: "高",
    summary: "政策判断、国債買入れ、物価・賃金への見方を確認する日。決定内容の公表時刻は未定。総裁会見は同日15:30からの予定。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "9月18日 会合終了後（時刻未定）",
  },
  {
    id: "us-industrial-production-2026-08",
    date: "2026-09-18",
    time: "22:15",
    title: "米鉱工業生産・設備稼働率（9月公表）",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "製造業、鉱業、公益事業の生産と設備稼働率を確認する統計。",
    sourceName: "Federal Reserve September 2026 Calendar",
    sourceUrl: "https://www.federalreserve.gov/newsevents/2026-september.htm",
    sourceTime: "9月18日 9:15 ET（夏時間）",
  },
  {
    id: "tse-respect-aged-day-2026",
    date: "2026-09-21",
    time: "休場",
    title: "東証現物市場 休場（敬老の日）",
    category: "休場",
    region: "日本",
    importance: "中",
    summary: "敬老の日に伴い、東証の現物市場は休場。先物・オプションの祝日取引とは日程が異なる。",
    sourceName: "日本取引所グループ 休業日一覧",
    sourceUrl: "https://www.jpx.co.jp/corporate/about-jpx/calendar/index.html",
    sourceTime: "9月21日 日本市場の取引日",
  },
  {
    id: "tse-citizens-holiday-2026",
    date: "2026-09-22",
    time: "休場",
    title: "東証現物市場 休場（国民の休日）",
    category: "休場",
    region: "日本",
    importance: "中",
    summary: "祝日に挟まれた休日に伴い、東証の現物市場は休場。先物・オプションの祝日取引とは日程が異なる。",
    sourceName: "日本取引所グループ 休業日一覧",
    sourceUrl: "https://www.jpx.co.jp/corporate/about-jpx/calendar/index.html",
    sourceTime: "9月22日 日本市場の取引日",
  },
  {
    id: "tse-autumnal-equinox-2026",
    date: "2026-09-23",
    time: "休場",
    title: "東証現物市場 休場（秋分の日）",
    category: "休場",
    region: "日本",
    importance: "中",
    summary: "秋分の日に伴い、東証の現物市場は休場。先物・オプションの祝日取引とは日程が異なる。",
    sourceName: "日本取引所グループ 休業日一覧",
    sourceUrl: "https://www.jpx.co.jp/corporate/about-jpx/calendar/index.html",
    sourceTime: "9月23日 日本市場の取引日",
  },
  {
    id: "us-new-home-sales-2026-08",
    date: "2026-09-24",
    time: "23:00",
    title: "米新築住宅販売件数 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "新築一戸建て住宅の販売件数、価格、在庫を確認する統計。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "9月24日 10:00 ET（夏時間）",
  },
  {
    id: "costco-fy26-q4",
    date: "2026-09-25",
    time: "06:00",
    title: "Costco FY2026 Q4 決算説明会",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "既存店売上高、会員更新率、粗利益率、消費動向を確認する小売大手の決算。",
    sourceName: "Costco Investor Relations",
    sourceUrl: "https://investor.costco.com/events-and-presentations/events/event-details/2026/Q4-2026-Earnings-Call/default.aspx",
    sourceTime: "9月24日 14:00 PT",
  },
  {
    id: "us-durable-goods-2026-08",
    date: "2026-09-25",
    time: "21:30",
    title: "米耐久財受注 2026年8月分・速報",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "耐久財の受注、出荷、受注残を確認する速報。輸送機器を除く受注や資本財の内訳も公表される。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "9月25日 8:30 ET（夏時間）",
  },
  {
    id: "boj-minutes-2026-07",
    date: "2026-09-28",
    time: "08:50",
    title: "日銀 金融政策決定会合議事要旨（7月30・31日分）",
    category: "金融政策",
    region: "日本",
    importance: "中",
    summary: "7月会合での景気・物価認識と政策判断をめぐる議論を確認する公表資料。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "9月28日 8:50 JST",
  },
  {
    id: "japan-services-ppi-2026-08",
    date: "2026-09-28",
    time: "08:50",
    title: "企業向けサービス価格指数 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "企業間で取引されるサービス価格の変化を確認する統計。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "9月28日 8:50 JST",
  },
  {
    id: "bls-jolts-2026-08",
    date: "2026-09-29",
    time: "23:00",
    title: "米JOLTS求人件数 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "10月の雇用統計前に求人件数、採用、離職の変化から労働需給を確認する。",
    sourceName: "BLS September 2026 Release Schedule",
    sourceUrl: "https://www.bls.gov/schedule/2026/09_sched.htm",
    sourceTime: "9月29日 10:00 ET",
  },
  {
    id: "bea-gdp-third-2026-q2",
    date: "2026-09-30",
    time: "21:30",
    title: "米GDP 2026年4-6月期・3次推計",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "実質GDPの改定値と産業別GDP、企業利益などを確認する公表日。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "9月30日 8:30 ET（夏時間）",
  },
  {
    id: "bea-pce-2026-08",
    date: "2026-09-30",
    time: "21:30",
    title: "米個人所得・個人消費支出（2026年8月分）",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "PCE物価と消費の次回確認日。FOMC後の金利見通しを点検する材料。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "9月30日 8:30 ET",
  },
  {
    id: "micron-fy26-q4",
    date: "2026-10-01",
    time: "05:30",
    title: "Micron Technology FY2026 Q4 決算説明会",
    category: "決算",
    region: "米国",
    importance: "高",
    summary: "DRAM、NAND、HBMの需要と価格、AI向けメモリー供給、次期見通しを確認する半導体決算。",
    sourceName: "Micron Investor Relations",
    sourceUrl: "https://investors.micron.com/news/press-release/2026/Micron-Technology-to-Report-Fiscal-Fourth-Quarter-Results-on-September-30-2026/default.aspx",
    sourceTime: "9月30日 14:30 MT",
  },
  {
    id: "boj-tankan-2026-09",
    date: "2026-10-01",
    time: "08:50",
    title: "日銀短観 2026年9月調査",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "企業の業況判断、価格判断、設備投資計画を幅広く確認する四半期調査。日銀の景気判断にも使われる。",
    sourceName: "日本銀行 統計データ公表予定",
    sourceUrl: "https://www.boj.or.jp/statistics/outline/",
    sourceTime: "10月1日 8:50 JST",
  },
  {
    id: "boj-opinions-2026-09",
    date: "2026-10-01",
    time: "08:50",
    title: "日銀 金融政策決定会合の主な意見（9月17・18日分）",
    category: "金融政策",
    region: "日本",
    importance: "中",
    summary: "9月会合で示された経済・物価情勢と金融政策運営に関する主な意見を確認する資料。議事要旨とは別の公表。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "10月1日 8:50 JST",
  },
  {
    id: "ism-manufacturing-2026-09",
    date: "2026-10-01",
    time: "23:00",
    title: "米ISM製造業景況指数 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "10月の米景気確認の起点となる製造業景況指数。新規受注、雇用、価格の変化を見る。",
    sourceName: "ISM Report Release Date Calendar",
    sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/rob-report-calendar/",
    sourceTime: "10月1日 10:00 ET",
  },
  {
    id: "tokyo-cpi-2026-09",
    date: "2026-10-02",
    time: "08:30",
    title: "東京都区部CPI 2026年9月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "10月以降の日銀観測を考えるうえでの先行物価指標。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/detail/00200573/202610020830",
    sourceTime: "10月2日 8:30 JST",
  },
  {
    id: "bls-employment-2026-09",
    date: "2026-10-02",
    time: "21:30",
    title: "米雇用統計 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "FOMC後の労働市場を確認する重要指標。景気減速と賃金インフレの両面を見る。",
    sourceName: "BLS Employment Situation Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
    sourceTime: "10月2日 8:30 ET",
  },
  {
    id: "japan-consumer-confidence-2026-09",
    date: "2026-10-05",
    time: "14:00",
    title: "消費動向調査 2026年9月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "消費者態度指数と暮らし向き、収入、雇用などの見通しを確認する調査。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "10月5日 14:00 JST",
  },
  {
    id: "ism-services-2026-09",
    date: "2026-10-05",
    time: "23:00",
    title: "米ISM非製造業景況指数 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "サービス需要、雇用、投入価格の変化から米国の内需とインフレ圧力を確認する。",
    sourceName: "ISM Report Release Date Calendar",
    sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/rob-report-calendar/",
    sourceTime: "10月5日 10:00 ET",
  },
  {
    id: "japan-leading-index-2026-08",
    date: "2026-10-07",
    time: "14:00",
    title: "景気動向指数 2026年8月分・速報",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "景気の現状と先行きを示す一致指数・先行指数の速報。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "10月7日 14:00 JST",
  },
  {
    id: "fomc-minutes-2026-09",
    date: "2026-10-08",
    time: "03:00",
    title: "FOMC議事要旨（2026年9月会合）",
    category: "金融政策",
    region: "米国",
    importance: "中",
    summary: "9月会合での政策判断、インフレ・雇用リスク、今後の金利経路をめぐる議論を確認する。",
    sourceName: "Federal Reserve FOMC Calendars",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceTime: "10月7日 14:00 ET",
  },
  {
    id: "fast-retailing-fy26",
    date: "2026-10-08",
    time: "未定",
    title: "ファーストリテイリング 2026年8月期 通期決算",
    category: "決算",
    region: "日本",
    importance: "高",
    summary: "国内外のユニクロ、ジーユーの業績と翌期の会社計画を確認する決算発表。発表時刻は公式カレンダーに未掲載。",
    sourceName: "ファーストリテイリング IRカレンダー",
    sourceUrl: "https://www.fastretailing.com/jp/ir/calendar/",
    sourceTime: "10月8日 JST（時刻未公表）",
  },
  {
    id: "tse-sports-day-2026",
    date: "2026-10-12",
    time: "休場",
    title: "東証現物市場 休場（スポーツの日）",
    category: "休場",
    region: "日本",
    importance: "中",
    summary: "スポーツの日に伴い、東証の現物市場は休場。先物・オプションの祝日取引とは日程が異なる。",
    sourceName: "日本取引所グループ 休業日一覧",
    sourceUrl: "https://www.jpx.co.jp/corporate/about-jpx/calendar/index.html",
    sourceTime: "10月12日 日本市場の取引日",
  },
  {
    id: "bls-cpi-2026-09",
    date: "2026-10-14",
    time: "21:30",
    title: "米CPI 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "次回FOMC前の物価確認。サービス価格とコア指数の粘着性が焦点。",
    sourceName: "BLS CPI Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
    sourceTime: "10月14日 8:30 ET",
  },
  {
    id: "fed-beige-book-2026-10",
    date: "2026-10-15",
    time: "03:00",
    title: "米ベージュブック（地区連銀経済報告）",
    category: "金融政策",
    region: "米国",
    importance: "中",
    summary: "各地区の企業などへの聞き取りに基づく景気、雇用、価格動向を確認する報告。",
    sourceName: "Federal Reserve October 2026 Calendar",
    sourceUrl: "https://www.federalreserve.gov/newsevents/2026-october.htm",
    sourceTime: "10月14日 14:00 ET（夏時間）",
  },
  {
    id: "japan-machinery-orders-2026-08",
    date: "2026-10-15",
    time: "08:50",
    title: "機械受注統計 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "設備投資の先行指標。船舶・電力を除く民需などの受注動向を確認する。",
    sourceName: "内閣府 景気統計公表予定",
    sourceUrl: "https://www.esri.cao.go.jp/jp/stat/stat-schedule.html",
    sourceTime: "10月15日 8:50 JST",
  },
  {
    id: "bls-ppi-2026-09",
    date: "2026-10-15",
    time: "21:30",
    title: "米PPI 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "10月FOMC前に企業段階の物価圧力を確認する指標。財・サービス価格の内訳を見る。",
    sourceName: "BLS PPI Release Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/ppi.htm",
    sourceTime: "10月15日 8:30 ET",
  },
  {
    id: "us-retail-sales-2026-09",
    date: "2026-10-15",
    time: "21:30",
    title: "米小売売上高 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "FOMC前に個人消費の強弱を確認する指標。自動車を除く売上や業種別の動向を見る。",
    sourceName: "U.S. Census Monthly Retail Trade Schedule",
    sourceUrl: "https://www.census.gov/retail/release_schedule.html",
    sourceTime: "10月15日 8:30 ET",
  },
  {
    id: "us-industrial-production-2026-09",
    date: "2026-10-16",
    time: "22:15",
    title: "米鉱工業生産・設備稼働率（10月公表）",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "製造業、鉱業、公益事業の生産と設備稼働率を確認する統計。",
    sourceName: "Federal Reserve October 2026 Calendar",
    sourceUrl: "https://www.federalreserve.gov/newsevents/2026-october.htm",
    sourceTime: "10月16日 9:15 ET（夏時間）",
  },
  {
    id: "us-housing-starts-2026-09",
    date: "2026-10-20",
    time: "21:30",
    title: "米住宅着工・建設許可件数 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "住宅着工、建設許可、竣工件数から住宅建設の動向を確認する統計。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "10月20日 8:30 ET（夏時間）",
  },
  {
    id: "japan-cpi-2026-09",
    date: "2026-10-23",
    time: "08:30",
    title: "全国CPI 2026年9月分",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "10月の日銀会合前に全国の物価基調を確認する重要指標。生鮮食品・エネルギーを除く指数も見る。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/statistics/00200573",
    sourceTime: "10月23日 8:30 JST",
  },
  {
    id: "us-durable-goods-2026-09",
    date: "2026-10-27",
    time: "21:30",
    title: "米耐久財受注 2026年9月分・速報",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "耐久財の受注、出荷、受注残を確認する速報。輸送機器や資本財の内訳を確認する。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "10月27日 8:30 ET（夏時間）",
  },
  {
    id: "us-new-home-sales-2026-09",
    date: "2026-10-27",
    time: "23:00",
    title: "米新築住宅販売件数 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "新築一戸建て住宅の販売件数、価格、在庫を確認する統計。",
    sourceName: "U.S. Census Economic Indicator Release Schedule",
    sourceUrl: "https://www.census.gov/economic-indicators/calendar-listview.html",
    sourceTime: "10月27日 10:00 ET（夏時間）",
  },
  {
    id: "fomc-2026-10",
    date: "2026-10-29",
    time: "03:00",
    title: "FOMC声明・政策金利発表",
    category: "金融政策",
    region: "米国",
    importance: "高",
    summary: "10月会合の政策金利、声明文、議長会見を確認する日。SEPは公表されない会合。",
    sourceName: "Federal Reserve FOMC Calendars",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceTime: "10月28日 14:00 ET",
  },
  {
    id: "bea-gdp-advance-2026-q3",
    date: "2026-10-29",
    time: "21:30",
    title: "米GDP 2026年7-9月期・1次推計",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "7-9月期の実質GDPを初めて公表する日。個人消費、設備投資、純輸出などの内訳を確認する。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "10月29日 8:30 ET（夏時間）",
  },
  {
    id: "bea-pce-2026-09",
    date: "2026-10-29",
    time: "21:30",
    title: "米個人所得・個人消費支出（2026年9月分）",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "個人所得、個人消費支出、PCE価格指数とコア指数を確認する統計。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "10月29日 8:30 ET（夏時間）",
  },
  {
    id: "tokyo-cpi-2026-10",
    date: "2026-10-30",
    time: "08:30",
    title: "東京都区部CPI 2026年10月分",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "日銀会合当日に公表される先行物価指標。サービス価格や基調的な物価の動きを確認する。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/statistics/00200573",
    sourceTime: "10月30日 8:30 JST",
  },
  {
    id: "boj-mpm-2026-10",
    date: "2026-10-30",
    time: "未定",
    title: "日銀 金融政策決定会合・展望レポート",
    category: "金融政策",
    region: "日本",
    importance: "高",
    summary: "政策判断に加え、経済・物価見通しを示す展望レポートを公表する会合。同日に総裁会見も行われる。",
    sourceName: "日本銀行 金融政策決定会合日程",
    sourceUrl: "https://www.boj.or.jp/mopo/mpmsche_minu/index.htm",
    sourceTime: "10月30日 会合終了後に結果公表",
  },
];
