export type CalendarEventCategory = "決算" | "経済指標" | "金融政策";
export type CalendarEventRegion = "日本" | "米国";
export type CalendarEventImportance = "高" | "中";

export type MarketCalendarEvent = {
  id: string;
  date: string;
  time: string;
  title: string;
  category: CalendarEventCategory;
  region: CalendarEventRegion;
  importance: CalendarEventImportance;
  summary: string;
  sourceName: string;
  sourceUrl: string;
  sourceTime?: string;
};

export const marketCalendarReviewedAt = "2026-08-23";

export const marketCalendarEvents: MarketCalendarEvent[] = [
  {
    id: "bea-pce-2026-07",
    date: "2026-08-26",
    time: "21:30",
    title: "米個人所得・個人消費支出（2026年7月分）",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "PCE物価と個人消費の確認日。FRBの物価判断と消費関連株の見方に関係しやすい。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule",
    sourceTime: "8月26日 8:30 ET",
  },
  {
    id: "bea-gdp-second-2026-q2",
    date: "2026-08-26",
    time: "21:30",
    title: "米GDP 2026年4-6月期・2次推計",
    category: "経済指標",
    region: "米国",
    importance: "中",
    summary: "企業利益とGDP改定の確認日。金利、景気敏感株、ドル円の材料になり得る。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "8月26日 8:30 ET",
  },
  {
    id: "nvidia-fy27-q2",
    date: "2026-08-27",
    time: "06:00",
    title: "NVIDIA FY2027 Q2 決算説明会",
    category: "決算",
    region: "米国",
    importance: "高",
    summary: "AI半導体、データセンター需要、次世代GPU供給を確認する重要決算。",
    sourceName: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/events-and-presentations/events-and-presentations/event-details/2026/NVIDIA-2nd-Quarter-FY27-Financial-Results/default.aspx",
    sourceTime: "8月26日 14:00 PT",
  },
  {
    id: "salesforce-fy27-q2",
    date: "2026-08-27",
    time: "朝",
    title: "Salesforce FY2027 Q2 決算",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "AI機能とソフトウェア需要、サブスクリプション成長の確認材料。",
    sourceName: "Salesforce Investor Relations",
    sourceUrl: "https://investor.salesforce.com/news/news-details/2026/Salesforce-Announces-Date-of-Second-Quarter-Fiscal-2027-Earnings-Release-and-Webcast/default.aspx",
    sourceTime: "8月26日 米国市場引け後",
  },
  {
    id: "tokyo-cpi-2026-08",
    date: "2026-08-28",
    time: "08:30",
    title: "東京都区部CPI 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "全国CPIに先行する物価指標。日銀観測と円金利の確認材料。",
    sourceName: "総務省統計局 消費者物価指数",
    sourceUrl: "https://www.stat.go.jp/data/cpi/sokuhou/tsuki/index-z.html",
    sourceTime: "8月28日 8:30 JST",
  },
  {
    id: "dell-fy27-q2",
    date: "2026-09-02",
    time: "05:30",
    title: "Dell Technologies FY2027 Q2 決算説明会",
    category: "決算",
    region: "米国",
    importance: "中",
    summary: "AIサーバー需要、インフラ投資、企業IT支出を確認する決算。",
    sourceName: "Dell Technologies Investor Relations",
    sourceUrl: "https://delltechnologies.gcs-web.com/",
    sourceTime: "9月1日 15:30 CDT",
  },
  {
    id: "bls-employment-2026-08",
    date: "2026-09-04",
    time: "21:30",
    title: "米雇用統計 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "雇用者数、失業率、賃金の確認日。FRB観測と株式・債券・為替に影響しやすい。",
    sourceName: "BLS Employment Situation Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
    sourceTime: "9月4日 8:30 ET",
  },
  {
    id: "japan-gdp-second-2026-q2",
    date: "2026-09-08",
    time: "08:50",
    title: "日本GDP 2026年4-6月期・2次速報",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "内需、設備投資、企業収益の改定を確認する日。日本株全体の景気認識に関係する。",
    sourceName: "内閣府 経済社会総合研究所",
    sourceUrl: "https://www.esri.cao.go.jp/jp/sna/kouhyou/kouhyou_top.html",
    sourceTime: "9月8日 8:50 JST",
  },
  {
    id: "bls-cpi-2026-08",
    date: "2026-09-11",
    time: "21:30",
    title: "米CPI 2026年8月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "インフレ再加速の有無を確認する指標。金利、グロース株、ドル円の重要材料。",
    sourceName: "BLS CPI Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
    sourceTime: "9月11日 8:30 ET",
  },
  {
    id: "fomc-2026-09",
    date: "2026-09-17",
    time: "03:00",
    title: "FOMC声明・政策金利発表",
    category: "金融政策",
    region: "米国",
    importance: "高",
    summary: "SEP付き会合。政策金利、声明文、議長会見、ドットチャートを確認する日。",
    sourceName: "Federal Reserve FOMC Calendars",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceTime: "9月16日 14:00 ET",
  },
  {
    id: "japan-cpi-2026-08",
    date: "2026-09-18",
    time: "08:30",
    title: "全国CPI 2026年8月分",
    category: "経済指標",
    region: "日本",
    importance: "高",
    summary: "日本の物価基調を確認する指標。日銀会合と同日に重なり、円金利の材料になりやすい。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/statistics/00200573",
    sourceTime: "9月18日 8:30 JST",
  },
  {
    id: "boj-mpm-2026-09",
    date: "2026-09-18",
    time: "15:30",
    title: "日銀 金融政策決定会合・総裁会見",
    category: "金融政策",
    region: "日本",
    importance: "高",
    summary: "政策判断、国債買入れ、物価・賃金への見方を確認する日。",
    sourceName: "日本銀行 公表予定",
    sourceUrl: "https://www.boj.or.jp/about/calendar/index.htm",
    sourceTime: "9月18日 15:30 JST",
  },
  {
    id: "bea-pce-2026-08",
    date: "2026-09-30",
    time: "21:30",
    title: "米個人所得・個人消費支出（2026年8月分）",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "PCE物価と消費の次回確認日。FOMC後の金利見通しを点検する材料。",
    sourceName: "BEA Release Schedule",
    sourceUrl: "https://www.bea.gov/news/schedule/full",
    sourceTime: "9月30日 8:30 ET",
  },
  {
    id: "tokyo-cpi-2026-09",
    date: "2026-10-02",
    time: "08:30",
    title: "東京都区部CPI 2026年9月分",
    category: "経済指標",
    region: "日本",
    importance: "中",
    summary: "10月以降の日銀観測を考えるうえでの先行物価指標。",
    sourceName: "e-Stat 消費者物価指数 公表予定",
    sourceUrl: "https://www.e-stat.go.jp/release-calendar/detail/00200573/202610020830",
    sourceTime: "10月2日 8:30 JST",
  },
  {
    id: "bls-employment-2026-09",
    date: "2026-10-02",
    time: "21:30",
    title: "米雇用統計 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "FOMC後の労働市場を確認する重要指標。景気減速と賃金インフレの両面を見る。",
    sourceName: "BLS Employment Situation Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
    sourceTime: "10月2日 8:30 ET",
  },
  {
    id: "bls-cpi-2026-09",
    date: "2026-10-14",
    time: "21:30",
    title: "米CPI 2026年9月分",
    category: "経済指標",
    region: "米国",
    importance: "高",
    summary: "次回FOMC前の物価確認。サービス価格とコア指数の粘着性が焦点。",
    sourceName: "BLS CPI Schedule",
    sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
    sourceTime: "10月14日 8:30 ET",
  },
];
